### ISSUE TITLE
Armadillo doesn't seem to adhere to session timeout of 30 min

### ISSUE THREAD

**Issue by timcadman** [molgenis/molgenis-service-armadillo#121]
How to reproduce:
Log in via Elixir and wait for 15 mins, and the session times out.

**Comment by sidohaakma** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Armadillo session timeout is not 30 minutes](https://trello.com/c/xIToKWUb/833-armadillo-session-timeout-is-not-30-minutes)

**Comment by fdlk** [comment]
I think we set `server.servlet.session.timeout` to 30 minutes [in the helm chart](https://github.com/molgenis/molgenis-ops-helm/blob/3b3fe17697d7a3024d0e5e4a53805352268a5bdb/charts/molgenis-armadillo/questions.yml#L138), here we leave the [spring boot default](https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html#server.servlet.session.timeout) alone.

**Comment by sidohaakma** [comment]
I think this could be due to the fact that when something goes wrong in the analysis the session is terminated. This works as intended. We need to harvest the error messages and feed it back to the DataSHIELD team.

**Comment by mswertz** [comment]
We speculate this is part of the Jupyter issue

**Comment by clemens-tolboom** [comment]
Testing on localhost:8080 as **admin user** using settings

```yml
server:
  servlet:
    session:
      timeout: 1m
```

I am kicked out the session in 1 minute time trying to switch between projects and users.

# UI

The UI could be friendlier

<img width="560" alt="image" src="https://github.com/molgenis/molgenis-service-armadillo/assets/371014/a6149c54-d7ca-44f1-8ef8-2e84acc2a272">

**Comment by clemens-tolboom** [comment]
Session checks seems to occur each minute ...

```
tail -f logs/armadillo.log | grep "Start expire sessions" -A 5
```
print found lines + 5 **A**fter
```log
2024-02-20 17:10:55.105 [Catalina-utility-1|] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1708445455101 sessioncount 0
2024-02-20 17:11:55.131 [Catalina-utility-2|] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1708445515130 sessioncount 3
2024-02-20 17:12:55.152 [Catalina-utility-1|] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1708445575152 sessioncount 3
2024-02-20 17:13:55.172 [Catalina-utility-1|] DEBUG o.a.catalina.session.ManagerBase - Start expire sessions StandardManager at 1708445635172 sessioncount 2
```

**Comment by clemens-tolboom** [comment]
It seems reproducible but is still uncertain calling increasing `lambda`

```R
ds.Lasso_CVInSite(
  X = "x_mat",
  Y = "y_mat",
  type = "regress",
  nlambda = 2,
  lam_ratio = 0.01,
  datasources = conns,
  nDigits = 4,
  nfolds = 2)
```

https://github.com/transbioZI/dsMTLClient/blob/main/R/ds.Lasso.R

**Comment by timcadman** [comment]
However it has now been resolved by increasing the JWT token duration on the authentication server

**Comment by clemens-tolboom** [comment]
We now need to refresh the token from within Armadillo

**Comment by StuartWheater** [comment]
I looked at this a while ago, it appeared the changes needed are relatively easy. If the JWT needs refreshing the http(s) request will return a particular http status code, the JWT can be refreshed using the appropriate function, and the request reissued with the new JWT.

If memory serves only very few places in the code need to be changed.

**Comment by timcadman** [comment]
Follow up issue is #669
