### ISSUE TITLE
404 message when saving workspace

### ISSUE THREAD

**Issue by timcadman** [molgenis/molgenis-service-armadillo#124]
```
datashield.workspace_save(conns, "bmi_poc_sec_2")
Error: Client error: (404) Not Found
```

**Comment by timcadman** [comment]
No I've worked this one out - it was an error triggered by their not being sufficient disk space to save the workspace. It would be helpful if it could state this in the error (though not sure if you have control over this).

**Comment by timcadman** [comment]
Updated issue to make clearer. As far as I know this is still an issue.

**Comment by clemens-tolboom** [comment]
We have to check while saving a workspace we have enough storage

1. org.molgenis.armadillo.controller.DataController#saveUserWorkspace
1. https://github.com/molgenis/molgenis-service-armadillo/blob/e64e2994f245969889e689b8c245d5bee572c6c2/armadillo/src/main/java/org/molgenis/armadillo/command/impl/CommandsImpl.java#L197-L208
1. https://github.com/molgenis/molgenis-service-armadillo/blob/390d683a1f70043790e190e065e9545bf3243e86/armadillo/src/main/java/org/molgenis/armadillo/storage/LocalStorageService.java#L110-L126

**Comment by timcadman** [comment]
Dick has checked and the largest workspace currently saved on BiB server is 1.3gb

**Comment by StuartWheater** [comment]
You could try the algorithm:

1. Write the shadow workspace
2. Cause a "filesystem sync" to persistent storage
3. If (1) and (2) successful: Remove original workspace
4. If (3) successful: Rename shadow workspace to original workflow
5. Cause a "filesystem sync" to persistent storage
6. Repeat (4) and (5) until successful

This will require the running of a crash recovery process on machine restart, to ensure all shadow workspace have been renamed.
