### ISSUE TITLE
dh.tidyEnv does not work on the armadillo

### ISSUE THREAD

**Issue by cocopizzi** [molgenis/molgenis-service-armadillo#147]
After having downloaded all the needed packages and logged in to access the alspac data (the same with the eden data), when I run this script, the environment gets not cleaned up:

core_nonrep <- c("child_id", "mother_id", "preg_no", "child_no",  "cohort_id",  
                 "agebirth_m_y", "parity_m", "abroad_mo",  "breastfed_ever")

datashield.assign.table(
  opals['alspac'], "core_nonrep", 
  "lc19/2_1_core_1_3/non_rep", 
  variables=core_nonrep
)

ds.recodeValues(
  var.name = "core_nonrep$parity_m",
  values2replace.vector = c(0, 1, 2, 3, 4),
  new.values.vector = c(0, 1, 1, 1, 1),
  newobj = "parity_bin",
  datasources= opals)

ds.dataFrame(
  x = c("core_nonrep",  "parity_bin"),
  newobj = "core_nonrep",  
  datasources= opals)

dh.tidyEnv(
  obj =  "parity_bin", 
  type = "remove")

**Comment by sidohaakma** [comment]
This is a problem within [dsHelper](https://github.com/lifecycle-project/ds-helper/issues/110)
