### ISSUE TITLE
Login into Armadillo using DSI

### ISSUE THREAD

**Issue by StuartWheater** [molgenis/molgenis-service-armadillo#156]
I am attempting to test dsBase/dsBaseClient v6.2, with Armadillo (molgenis/armadillo:latest). But when attempting to login to Armadillo using DSI and authenticating using `auth.molgenis.org` I get the error below:

`Error: Internal server error: Error creating bean with name 'scopedTarget.commandsImpl' defined in file [/app/classes/org/molgenis/armadillo/command/impl/CommandsImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.molgenis.armadillo.command.impl.CommandsImpl]: Constructor threw exception; nested exception is org.molgenis.r.exceptions.ConnectionCreationFailedException: org.rosuda.REngine.Rserve.RserveException: Cannot connect: Connection refused (Connection refused)`

Is this problem due to `auth.molgenis.org` not being online at the moment? Could you point to current documentation on how to authenticate tests?

Stuart

**Comment by StuartWheater** [comment]
Correction: "auth.molgenis.org" is online, just not responding to "ping".

**Comment by mswertz** [comment]
@StuartWheater is this still an issue?

**Comment by StuartWheater** [comment]
I found a workaround. By setting SPRING_PROFILES_ACTIVE to "development,docker-compose" and removing SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI and SPRING_SECURITY_OAUTH2_RESOURCESERVER_OPAQUETOKEN_CLIENT_ID in armadillo service's environment section in the docker-compose.yml's for the deployment, I could login using a standard username and default password.
