### ISSUE TITLE
Demo Docker set up doesn't allow access via non-localhost addresses?

### ISSUE THREAD

**Issue by tombisho** [molgenis/molgenis-service-armadillo#445]
Hi,

I have been trying out the Docker arrangement for demos/testing. I can get the container to start, however, it is not possible to access the UI. I have a VM on my local desktop where I am running Armadillo. The VM has the IP address 192.168.56.100, so I need to use this to access rather than localhost. However, it seems like Armadillo blocks this:

`12:45:08.831 [http-nio-8080-exec-1|] INFO  o.m.armadillo.audit.AuditLogger - AuditEvent [timestamp=2023-05-22T12:45:08.824678929Z, principal=anonymousUser, type=AUTHORIZATION_FAILURE, data={details=WebAuthenticationDetails [RemoteIpAddress=192.168.56.1, SessionId=null], type=org.springframework.security.access.AccessDeniedException, message=Access is denied}]`

Instead, I have been able to use Stuart's docker-compose.yml to get me going, but this is not available for other users who might want to try things out!

Thanks

Tom

**Comment by tombisho** [comment]
Hi, I note that in the images, the "basic" profile is not available (the demo guide says "These run in 'basic' profile."):

![image](https://github.com/molgenis/molgenis-service-armadillo/assets/8521654/af4a1ef6-109f-488a-8354-27f243274543)

Maybe this does not help?

**Comment by marikaris** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [🦟 Bugs](https://trello.com/c/MicPC91Y/1063-%F0%9F%A6%9F-bugs)

**Comment by clemens-tolboom** [comment]
We can close this as #248 has a public image(s) of which the latest `datashield/armadillo_citest:1.1.0` shows the web ui.
