### ISSUE TITLE
Roles - READ, ADMIN

### ISSUE THREAD

**Issue by magdakozlovska** [molgenis/molgenis-service-armadillo#459]
As a READ, I cannot see any projects. I get this error message: 
Error: Could not load projects: ApiError: You don't have correct permissions. Please contact the administrator.

According to the documentation 
https://github.com/molgenis/molgenis-service-armadillo/blob/master/doc/adr/0007-use-roles-to-authorise-users-to-use-data.md, 
READ should be able to see the data in the shared folder(s) to which they have access.

As a ADMIN, I see everything, I can also change/delete the tables or change roles of other people or delete them. 

Could you please modify/clarify the roles?

**Comment by marikaris** [comment]
Hi Magda, 
The userinterface for armadillo is solely meant for superusers/admins to manage users/projects/profiles. Therefor accounts with read permissions will not be able to view data in the user interface. They can however do analysis using R. For further questions, could you please contact molgenis-support@umcg.nl? They will be able to help you. We'd like to keep this issue tracker for bugs in the code :-)
