### ISSUE TITLE
MolgenisArmadillo::armadillo.list_projects() --> Error: You are not logged in.

### ISSUE THREAD

**Issue by magdakozlovska** [molgenis/molgenis-service-armadillo#460]
When I try to run MolgenisArmadillo::armadillo.list_projects(), I get errors even though I'm logged in. 

> \# steps needed to delete project inma
> MolgenisArmadillo::armadillo.list_projects()
Error: You are not logged in.
         Please log in with armadillo.login('<YOUR_SERVER>')

My colleague gets the same. We did all the previous steps. 

Could you please take a look at it? 

Thank you

**Comment by marikaris** [comment]
Could you please contact molgenis-support@umcg.nl for this? I don't think this is a bug, but we would like to help you to get it to work.
