### ISSUE TITLE
bug: service script should add configuration instead of replace application.yml

### ISSUE THREAD

**Issue by clemens-tolboom** [molgenis/molgenis-service-armadillo#488]
We used the `application.template.yml` testing migration from v2 to v3

https://github.com/molgenis/molgenis-service-armadillo/blob/265bb22feb59b4349f25fc97ab4cf233fb06180b/scripts/install/armadillo-setup.sh#L122

should be change into `SPRING.CONFIG.ADDITIONAL-LOCATION` (what about the dash?)

**Comment by DickPostma** [comment]
It looks like environment with ., wont work on systemd. 
I tested it with this config and that seems to work:
Environment=SPRING_CONFIG_ADDITIONAL_LOCATION=/etc/armadillo/application.yml
