### ISSUE TITLE
Make Armadillo Rock profile only

### ISSUE THREAD

**Issue by clemens-tolboom** [molgenis/molgenis-service-armadillo#519]
As discussed it would make lot of sense to only use Rock docker image. See PR #522

Impact on at least

- [x] `scripts/release/release-test.R`
- [x] `data/system/profiles.json` (default profile, whitelist, ?) which is from `armadillo/src/main/resources/application.yml`
- [x] `r/src/main/java/org/molgenis/r/RServerConnectionFactory.java` and peers

## Upgrade considerations

- [ ] What packages are available in rock images?
- [ ] When are these published?
- [x] Could we maintain a rock only branch + release schedule?

## Base config

- datashield/rock-base:latest

**Comment by clemens-tolboom** [comment]
## Custom branch for rserve?

Tagging the PR branch with **ROCKONLY** gives `build/libs/molgenis-armadillo-3.4.0-ROCKONLY.jar` so we could build particular versions but that would become cumbersome.

For managing flavours of Armadillo in this case 2 versions we should make a different branching scheme.

- master becomes the rock only
- v3.* becomes a separate branch for which we then could provide bug fixes and back ports from master

Is this needed?

**Comment by clemens-tolboom** [comment]
Can we close this regarding the open tasks ... do they need new issues?

**Comment by timcadman** [comment]
Armadillo 4 is Rock-only
