### ISSUE TITLE
Make profiles autostart after reboot

### ISSUE THREAD

**Issue by DickPostma** [molgenis/molgenis-service-armadillo#531]
In the profile list you start docker-containers like armadillo-rserver or xenon. 

After an reboot the docker containers are in a stopped state and should be automatically be started.

**Comment by clemens-tolboom** [comment]
We could use armadillo API to get list of images or just the `data/system/profiles.json`

```zsh
jq '.profiles | .[] | .name' data/system/profiles.json
"rock"
"default"
"xenon"
```

Then `curl ... http://localhost:8080/ds-profiles/<name>/start` each of them

Is it ok to have a script for this?

**Comment by clemens-tolboom** [comment]
Currently I have a `dockerctl` which I rename to `armadilloctl`. It needs small changes from the @DickPostma zip version showed.

- change restartAll to start profile from Armadillo config

An server special script can call it to `armadilloctl restartAll` or sequence of `armadilloctl start <name>`
