### ISSUE TITLE
Install v3.4 using old v3.4 docs

### ISSUE THREAD

**Issue by clemens-tolboom** [molgenis/molgenis-service-armadillo#616]
To test a v3.4 installation for upgrade we need the docs online. For now simplest is to:

- [x] Read but **not wget** the **old v3.4.0** install guide https://github.com/molgenis/molgenis-service-armadillo/tree/v3.4.0
- [x] Make sure to use old versions of scripts
- [x] https://raw.githubusercontent.com/molgenis/molgenis-service-armadillo/v3.4.0/scripts/install/armadillo-setup.sh
- [x] edit script to fetch the old version instead of master
  - https://github.com/molgenis/molgenis-service-armadillo/blob/v3.4.0/scripts/install/conf/application.yml
  - https://raw.githubusercontent.com/molgenis/molgenis-service-armadillo/v3.4.0/scripts/install/armadillo-check-update.sh

### Running the old release-test.R

Make sure to checkout **v.3.4.0** branch

```
release git:(v3.4.0) ✗ git status
HEAD detached at v3.4.0
```

### Bugs on v3.4 setup

- cron symlink is wrong (there is no see `check-update.sh` https://github.com/molgenis/molgenis-service-armadillo/issues/616#issuecomment-1908178195
- Needed application.yml fix see https://github.com/molgenis/molgenis-service-armadillo/issues/616#issuecomment-1908281858
  - Login failed similar
  - PUT request failed is this same as Login

### Related

See #594 for upgrade instructions to v4.x

**Comment by RubenOPS** [comment]
```
ls -al /etc/cron.*

/etc/cron.weekly:
total 16
drwxr-xr-x   2 root root 4096 Jan 24 13:56 .
drwxr-xr-x 104 root root 4096 Jan 24 13:56 ..
-rw-r--r--   1 root root  102 Mar 23  2022 .placeholder
lrwxrwxrwx   1 root root   48 Jan 24 13:56 check-armadillo-update -> /usr/share/armadillo/application/check-update.sh
-rwxr-xr-x   1 root root 1020 Mar 17  2022 man-db
```

**Comment by clemens-tolboom** [comment]
We got two problems login and add user

- login user GET problem
- add user PUT

Adding the application.yml snippet works for v3.4.0

```
server:
  forward-headers-strategy: framework
  error:
    include-binding-errors: always
    include-message: always
```

**Comment by clemens-tolboom** [comment]
This needs update of master docs with warnings installing a v3.4

- [ ] Add notification on main install page
- [ ] Add separate file
- [ ] explain the problem
- [ ] list problems and fixes
  - download setup and edit
  - run setup
  - edit application.yaml
