### ISSUE TITLE
update docs uses armadillo 2 login block (R) style

### ISSUE THREAD

**Issue by erikzwart** [molgenis/molgenis-service-armadillo#633]
The R script examples in the docs contain the old style of login, is the rest of the script still valid using Armadillo 3/4?
https://github.com/molgenis/molgenis-service-armadillo/blob/7689be392fb7b8bf1922629f3a1266d6304313db/docs/DataSHIELD-datamanagement/1_MolgenisArmadillo.r#L21

**Comment by clemens-tolboom** [comment]
I think there are no links to this sub dir from https://molgenis.github.io/molgenis-service-armadillo/ ... did not search hard yet.

I think we could cleanup these?

**Comment by clemens-tolboom** [comment]
Closing as will be fixed by PR #641
