### ISSUE TITLE
Insight get too big a files ... 500MB log file

### ISSUE THREAD

**Issue by clemens-tolboom** [molgenis/molgenis-service-armadillo#658]
We should add size caps before querying log file or audit file

- [ ] max number of lines
- [ ] time interval 
- [ ] paging with default last `n` (1000) lines?
?

**Comment by StuartWheater** [comment]
One problem is that the querying log file or audit file have been proposed as a basis for detecting attempted disclosure. Not sure if that means logs need to be kept.

**Comment by clemens-tolboom** [comment]
This is a bug because of a `500 server error`

Most of the times OPS do log rotate ie `/var/log/armadillo/armadillo.log` daily (depending on size) and keep it for a month or 30 rotations.

For an audit file I'm not sure what a security protocol/officier needs and wants

For a browser to display 500MB is too hard. Downloading is I guess fine.

**Comment by mswertz** [comment]
I think we should indeed go for paging. What is an interesting proposition is to combine that with a search filter?

**Comment by clemens-tolboom** [comment]
Not sure how to combine this ... say we have a file of 10GB (exaggerated) with paging we reduce data sent to browser by reading from end ie `10KB` * page_size * page back which is fast:

- seek to `file size` - `10KB` * page_size * page
- read string for `10KB` * page_size`

![image](https://github.com/molgenis/molgenis-service-armadillo/assets/371014/36a9fc22-e76c-4b6d-a88a-2809441314f9)

Filtering on the raw file is heavy and removes context in browser.

**Comment by clemens-tolboom** [comment]
UI something like this where:

- pages are either fetched
  - from begin of file: page index >= 0
  - from end of file: page index < 0
- page size in KB / MB?

Note: file size is next to server time

![image](https://github.com/molgenis/molgenis-service-armadillo/assets/371014/95fdd23c-313d-4390-9364-59a07d2c9342)
