### ISSUE TITLE
Potential improvements for the Armadillo Upgrade 3-4 manual

### ISSUE THREAD

**Issue by RubenOPS** [molgenis/molgenis-service-armadillo#667]
I have some potential improvements for the Armadillo Upgrade 3-4 manual.

At step 3.2 (./armadillo-check-update.sh 4.x.y), I receive the message "Current version is not upgradeable" at the bottom of the output, even though the jar file is successfully downloaded. Whether the version is upgradeable or not seems irrelevant. Perhaps this instruction could be modified to say "You can run the script to download the new Armadillo version." This could prevent confusion by clarifying that upgrading is still possible despite the message.

![Step3-2](https://github.com/molgenis/molgenis-service-armadillo/assets/152260548/4559aad1-2f59-4867-a06a-b6cfe2f5e50a)

In step 4.1, there might be confusion about how to place "docker-run-in-container: false". It may not be immediately clear for some users whether it should be placed directly under "docker-management-enabled: true" or if the combination "docker-management-enabled: true: docker-run-in-container: false" should be added at the end of the file.

Checking the log files in step 5.4 would probably fit better under 'Troubleshooting' since it does not directly contribute to the installation process.

**Comment by marikaris** [comment]
@RubenOPS Could you maybe add a PR for this? You can simply do that by editing the file on github and create a PR branch when saving (github will ask you to)
