### ISSUE TITLE
I receive an error when attempting to upload a file using the UI

### ISSUE THREAD

**Issue by timcadman** [molgenis/molgenis-service-armadillo#671]
## How to reproduce
Attempt to upload a file to the demo server using the UI with admin login. Test case file size = 65mb

## Expected
File uploads with success message

## Observed
Failed with message:
`Error: ApiError: You don't have correct permissions. Please contact the administrator`

## Notes
This error does not occur when uploading a very small file (50kb)

**Comment by clemens-tolboom** [comment]
On dev server we still have

```yml
server:
  servlet:
    session:
      timeout: 1m
```
