### ISSUE TITLE
Service can not handle multiple users logging in and loading tables

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis-service-armadillo#70]
## How to reproduce
Open the JMX below in JMeter and run the test. 

Users: >1
Ramp-up: 3 seconds
Actions:
- Login
- Load GECKO tables

## Expected behaviour
All requests succeed

## Actual behaviour
Varying types of errors:
1. Rserve error: handshake failed
2. Rserve error: eval failed
3. Time-out

**Comment by fdlk** [comment]
Sessions stay alive for 30 minutes by default I think, so perhaps the users should logout too.

**Comment by fdlk** [comment]
Looks like the root cause is #61
