### ISSUE TITLE
Increasing "could not attach connection to Rsession" errors on moderate load

### ISSUE THREAD

**Issue by tommydeboer** [molgenis/molgenis-service-armadillo#73]
JMeter testplan setup:
![image](https://user-images.githubusercontent.com/5362890/85678618-f21e2e00-b6c8-11ea-91c3-06fac23ed45d.png)

Tested with 5 users. After a few minutes, more and more requests start to drop:

```
org.molgenis.armadillo.exceptions.ArmadilloSessionException: Could not attach connection to RSession
```

This effect persists: consecutive test runs will have more and more failing requests.

**Comment by fdlk** [comment]
Looks like the root cause is #61
